### ISSUE TITLE
Should handler methods be optional?

### ISSUE THREAD

**Issue by michaelfig** [Agoric/proposal-infix-bang#3]
Is there some sensible behaviour we can specify when passed a handler that's missing methods?

For example, what should the following do, or should it continue to be rejected?

```js
const handler = {
  POST(o, key, args) {
    return o[key](...args);
  }
};
```

**Comment by erights** [comment]
I think that the default behavior associated with missing handlers should be to throw an error. Note that this is already what would happen if you don't check for that case. Some uses of handled promises will support only POST by design, as Agoric's current system would. Others will support only POST and GET by design, as Waterken effectively did. Having the unsupported ones error is the right thing.
